#pragma once

#define VNR_MAJOR_VERSION 1
#define VNR_MINOR_VERSION 0
#define VNR_PATCH_VERSION 0

#define VERSION_TEXT(x) TEXT(x)
#define VERSION_STRINGIFY_EXPANDED(x) VERSION_TEXT(#x)
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_EXPANDED(x)

#define SKALE_COMPANY_NAME "SkaLe Studio"
#define SKALE_COPYRIGHT_STRING "Copyright SkaLe Studio. All Rights Reserved."
#define SKALE_PRODUCT_NAME "VeiNetRoute"
#define SKALE_PRODUCT_IDENTIFIER "VeiNetRoute"


#define VNR_VERSION_STRING \
	VERSION_STRINGIFY(VNR_MAJOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(VNR_MINOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(VNR_PATCH_VERSION)
