#pragma once

#define ENGINE_MAJOR_VERSION 1
#define ENGINE_MINOR_VERSION 0
#define ENGINE_PATCH_VERSION 0

#define VERSION_TEXT(x) TEXT(x)
#define VERSION_STRINGIFY_EXPANDED(x) VERSION_TEXT(#x)
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_EXPANDED(x)

#define SKALE_COMPANY_NAME "SkaLe Studio"
#define SKALE_COPYRIGHT_STRING "Copyright SkaLe Studio. All Rights Reserved."
#define SKALE_PRODUCT_NAME "VeiM Engine"
#define SKALE_PRODUCT_IDENTIFIER "VeimEngine"


#define ENGINE_VERSION_STRING \
	VERSION_STRINGIFY(ENGINE_MAJOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(ENGINE_MINOR_VERSION) \
	VERSION_TEXT(".") \
	VERSION_STRINGIFY(ENGINE_PATCH_VERSION)
